export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const COMPANY_SUCCESS = "COMPANY_SUCCESS";
export const LICENSE_SUCCESS = "LICENSE_SUCCESS";
export const LICENSE_FAIL = "LICENSE_FAIL";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SIDEBAR_COLLAPSE = "SIDEBAR_COLLAPSE";

